Repository CFenner/PyViCare, pull requests merged in 2024-08, with the labels that each got.

#5 chore(ci): modify release to use poetry
  .github/workflows/lint.yml
  .github/workflows/release.yml
  pyproject.toml
Labels: ci

#7 chore(ci): fix pypi project
  .github/workflows/release.yml
Labels: ci

#8 chore: fix project name
  pyproject.toml
Labels: maintenance

#11 chore: delete unused files
  .flake8
  .pylintrc
  Makefile
  publish.sh
  pyproject.toml
Labels: maintenance

#9 fix: correct unit getter for heating.gas.consumption.summary.dhw
  PyViCare/PyViCareGazBoiler.py
  tests/test_Vitodens100W.py
Labels: bugfix

#16 feat(deprecation): remove usage of deprecated data points
  PyViCare/PyViCareHeatPump.py
  PyViCare/PyViCareHeatingDevice.py
  tests/test_TestForMissingProperties.py
  tests/test_Vitocal250A.py
  tests/test_Vitocaldens222F.py
  tests/test_VitolaUniferral.py
Labels: enhancement

#17 chore(testdata): update test data for Vitocal250A
  tests/response/Vitocal250A.json
  tests/test_TestForMissingProperties.py
  tests/test_Vitocal250A.py
Labels: maintenance

#21 chore(renovate): add default label
  .github/renovate.json
Labels: maintenance

#19 feat: expose hysteresis value data points
  PyViCare/PyViCareHeatPump.py
  tests/test_TestForMissingProperties.py
  tests/test_Vitocal250A.py
Labels: new-feature

#23 fix: downgrade dependency to be in line with HA
  poetry.lock
  pyproject.toml
Labels: bugfix

#24 feat: add Vitoconnect Opto 2 / Heatbox2 as gateway
  PyViCare/PyViCareDeviceConfig.py
  PyViCare/PyViCareService.py
  tests/response/VitoconnectOpto2.json
  tests/test_PyViCareDeviceConfig.py
  tests/test_VitoconnectOpto2.py
Labels: new-feature

#26 chore(testdata): add test and response for Vitoladens 300-C
  PyViCare/PyViCareHeatingDevice.py
  tests/response/Vitoladens300-C_J3RA.json
  tests/test_Vitoladens300C.py
Labels: maintenance
